# Basic dependabot.yml file 
# with minimum configuration for maven and github-actions

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/ddk-parent/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"